version = 1

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/sagmans/serverpro"

[[analyzers]]
name = "shell"
enabled = true

  [analyzers.meta]
  dialect = "bash"

[[analyzers]]
name = "secrets"
enabled = true
